globalThis.NORTHSTAR_DEMO = Object.freeze({
  disclosure: "Interactive sample · Mock data · Runs entirely in your browser",
  sampleDate: "Sample data as of 8 August 2026",
  roadmapEfforts: Object.freeze([
    "Product Baseline",
    "Tenant Safeguards",
    "Release Packaging",
    "Beta Operations",
    "Launch Documentation",
    "Feedback Intake",
    "Shared Release Notes",
    "Partner Handoff",
    "Review Cadence",
    "Team Decision Export",
    "Alpha Cohort",
    "Learning Synthesis",
  ]),
  findResults: Object.freeze([
    Object.freeze({
      type: "Roadmap",
      title: "Public Beta Readiness",
      id: "roadmap:public-beta-readiness",
      phrase: "Prepare the first dependable release for design partners.",
      parent: "Northstar / Roadmaps",
      href: "#/roadmaps/public-beta-readiness",
    }),
    Object.freeze({
      type: "Gate",
      title: "Release candidate ready",
      id: "gate:release-candidate-ready",
      phrase: "Candidate evidence is ready for human acceptance review; the Gate is not passed.",
      parent: "Northstar / Public Beta Readiness",
      href: "#/gates/release-candidate-ready",
    }),
    Object.freeze({
      type: "Effort",
      title: "Release Packaging",
      id: "effort:release-packaging",
      phrase: "Prepare and verify the clean-install release bundle.",
      parent: "Northstar / Public Beta Readiness / Release candidate ready",
      href: "#/efforts/release-packaging",
    }),
    Object.freeze({
      type: "Managed native work",
      title: "Verify clean-install release bundle",
      id: "native:verify-clean-install-release-bundle",
      phrase: "Confirm that the fixed candidate bytes install and run without hidden state.",
      parent: "Northstar / Release Packaging / Delivery",
      href: "#/native-work/release-packaging",
    }),
    Object.freeze({
      type: "Asset",
      title: "Public Beta Readiness Review",
      id: "asset:public-beta-readiness-review",
      phrase: "Fixes the release evidence scope used for owner review.",
      parent: "Northstar / Assets",
      href: "#/assets/public-beta-readiness-review",
    }),
    Object.freeze({
      type: "Authority",
      title: "Reliability & Operations",
      id: "authority:reliability-operations",
      phrase: "Current accepted baseline for dependable Public Beta operations.",
      parent: "Northstar / Authorities",
      href: "#/authorities/reliability-operations",
    }),
    Object.freeze({
      type: "Planning Review",
      title: "Review the Public Beta release decision",
      id: "review:public-beta-release-decision",
      phrase: "Decide whether the fixed candidate evidence is sufficient for owner acceptance.",
      parent: "Northstar / Attention",
      href: "#/reviews/public-beta-release-decision",
    }),
    Object.freeze({
      type: "Audit",
      title: "Planning Audit",
      id: "audit:current-project-review",
      phrase: "Read the current review and accepted history alongside the pending decision.",
      parent: "Northstar / Audit",
      href: "#/audit",
    }),
  ]),
});
