globalThis.NORTHSTAR_DEMO = Object.freeze({
  disclosure:
    "Fixed-data static sample · Not a hosted Bearing project · Runs entirely in your browser",
  sampleDate: "Sample data as of 8 August 2026",
  roadmapEfforts: Object.freeze([
    "Product Baseline",
    "Tenant Safeguards",
    "Release Packaging",
    "Beta Operations",
    "Launch Documentation",
    "Feedback Intake",
    "Shared Release Notes",
    "Partner Handoff",
    "Review Cadence",
    "Team Decision Export",
    "Alpha Cohort",
    "Learning Synthesis",
  ]),
  findResults: Object.freeze([
    Object.freeze({
      type: "Roadmap",
      title: "Public Beta Readiness",
      id: "roadmap:public-beta-readiness",
      parent: "Northstar / Roadmaps",
      href: "#/roadmaps/public-beta-readiness",
    }),
    Object.freeze({
      type: "Gate",
      title: "Release candidate ready",
      id: "gate:release-candidate-ready",
      parent: "Northstar / Public Beta Readiness",
      href: "#/gates/release-candidate-ready",
    }),
    Object.freeze({
      type: "Effort",
      title: "Release Packaging",
      id: "effort:release-packaging",
      parent: "Northstar / Public Beta Readiness / Release candidate ready",
      href: "#/efforts/release-packaging",
    }),
    Object.freeze({
      type: "Managed native work",
      title: "Verify clean-install release bundle",
      id: "native:verify-clean-install-release-bundle",
      parent: "Northstar / Release Packaging / Delivery",
      href: "#/native-work/release-packaging",
    }),
    Object.freeze({
      type: "Asset",
      title: "Public Beta Readiness Review",
      id: "asset:public-beta-readiness-review",
      parent: "Northstar / Assets",
      href: "#/assets/public-beta-readiness-review",
    }),
    Object.freeze({
      type: "Authority",
      title: "Reliability & Operations",
      id: "authority:reliability-operations",
      parent: "Northstar / Authorities",
      href: "#/authorities/reliability-operations",
    }),
    Object.freeze({
      type: "Planning Review",
      title: "Review the Public Beta release decision",
      id: "review:public-beta-release-decision",
      parent: "Northstar / Attention",
      href: "#/reviews/public-beta-release-decision",
    }),
    Object.freeze({
      type: "Audit",
      title: "Planning Audit",
      id: "audit:current-project-review",
      parent: "Northstar / Audit",
      href: "#/audit",
    }),
  ]),
});
