import {
  ArrowLeft,
  ArrowRight,
  Check,
  ChevronDown,
  CircleAlert,
  ClipboardCheck,
  Copy,
  FileText,
  Grid2X2,
  Info,
  Link2,
  Menu,
  RefreshCw,
  Route,
  Search,
  TriangleAlert,
  X,
} from "lucide-react";

export const Icons = {
  arrow: ArrowRight,
  back: ArrowLeft,
  attention: TriangleAlert,
  asset: FileText,
  audit: ClipboardCheck,
  check: Check,
  copy: Copy,
  chevron: ChevronDown,
  close: X,
  menu: Menu,
  overview: Grid2X2,
  refresh: RefreshCw,
  roadmap: Route,
  search: Search,
  source: Link2,
  information: Info,
  unavailable: CircleAlert,
} as const;
